/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: LeanModularForms contributors
-/
import LeanModularForms.HeckeRIngs.GL2.Newforms
import LeanModularForms.Modularforms.Delta
import LeanModularForms.Modularforms.JacobiTheta

/-!
# The discriminant Δ is a Hecke eigenform

This file proves that the modular discriminant `Delta : CuspForm Γ(1) 12` is a Hecke
eigenform: for every `n : ℕ+`, the operator `T_n` acts on `Delta` as a scalar.

## Strategy

The space `S_12(Γ(1))` is one-dimensional, generated by `Delta` (since
`Module.finrank ℂ (CuspForm Γ(1) 12) = 1` and `Delta ≠ 0`). Hence any linear
endomorphism of `S_12(Γ(1))` (in particular `heckeT_n_cusp 12 n`) maps `Delta` to
a scalar multiple of itself.

The challenge is that `IsEigenform` is defined for cusp forms over `(Gamma1 N).map
(mapGL ℝ)` while `Delta` lives over `Γ(1) = (Gamma 1).map (mapGL ℝ)`. We bridge via
`Gamma 1 = Gamma1 1 = ⊤` (both equal the full SL(2, ℤ) at level 1).

## Main results

* `Delta_lvl1` — the discriminant viewed as a `CuspForm ((Gamma1 1).map (mapGL ℝ)) 12`
* `Delta_lvl1_ne_zero` — `Delta_lvl1 ≠ 0`
* `finrank_cuspForm_lvl1_weight12` — `dim S_12(Γ₁(1)) = 1`
* `Delta_lvl1_isEigenform` — `IsEigenform Delta_lvl1`
-/

namespace HeckeRing.GL2

open scoped MatrixGroups CongruenceSubgroup
open ModularForm UpperHalfPlane CongruenceSubgroup Matrix.SpecialLinearGroup

/-- `Gamma1 1 = ⊤` since the congruence conditions mod 1 are trivial. -/
lemma Gamma1_one_top : Gamma1 (1 : ℕ) = ⊤ := by
  ext γ
  simp only [Gamma1_mem, Subgroup.mem_top, iff_true]
  refine ⟨?_, ?_, ?_⟩ <;> exact Subsingleton.elim _ _

/-- `Gamma 1 = Gamma1 1` since both equal `⊤`. -/
lemma Gamma_one_eq_Gamma1_one : Gamma (1 : ℕ) = Gamma1 (1 : ℕ) := by
  rw [Gamma_one_top, Gamma1_one_top]

/-- The image under `mapGL ℝ` agrees for `Gamma 1` and `Gamma1 1`. -/
lemma map_Gamma_one_eq_map_Gamma1_one :
    (Gamma (1 : ℕ)).map (mapGL ℝ) = (Gamma1 (1 : ℕ)).map (mapGL ℝ) := by
  rw [Gamma_one_eq_Gamma1_one]

/-- The discriminant `Delta` viewed as a cusp form for `(Gamma1 1).map (mapGL ℝ)`.
The underlying function is the same as `Delta`; only the invariance subgroup changes
(but it's the same group). -/
noncomputable def Delta_lvl1 :
    CuspForm ((Gamma1 (1 : ℕ)).map (mapGL ℝ)) 12 where
  toFun := Delta
  slash_action_eq' γ hγ := by
    -- `γ ∈ (Gamma1 1).map (mapGL ℝ) = (Gamma 1).map (mapGL ℝ)`, so we can apply `Delta`'s invariance
    have hγ' : γ ∈ (Gamma (1 : ℕ)).map (mapGL ℝ) := by
      rw [map_Gamma_one_eq_map_Gamma1_one]; exact hγ
    exact Delta.slash_action_eq' γ hγ'
  holo' := Delta.holo'
  zero_at_cusps' {c} hc := by
    -- `IsCusp c ((Gamma1 1).map (mapGL ℝ))` ↔ `IsCusp c ((Gamma 1).map (mapGL ℝ))`
    have hc' : IsCusp c ((Gamma (1 : ℕ)).map (mapGL ℝ)) := by
      rw [map_Gamma_one_eq_map_Gamma1_one]; exact hc
    exact Delta.zero_at_cusps' hc'

@[simp]
lemma Delta_lvl1_apply (z : ℍ) : Delta_lvl1 z = Δ z := Delta_apply z

lemma Delta_lvl1_ne_zero : Delta_lvl1 ≠ 0 := by
  intro h
  have hI : Delta_lvl1 UpperHalfPlane.I = 0 := by rw [h]; rfl
  rw [Delta_lvl1_apply] at hI
  exact Δ_ne_zero UpperHalfPlane.I hI

/-- A linear equivalence between cusp forms over `(Gamma 1).map (mapGL ℝ)` and over
`(Gamma1 1).map (mapGL ℝ)`. The underlying function is the same; only the invariance
group changes (but it's the same group). -/
noncomputable def cuspForm_Gamma_one_equiv_Gamma1_one (k : ℤ) :
    CuspForm ((Gamma (1 : ℕ)).map (mapGL ℝ)) k ≃ₗ[ℂ]
    CuspForm ((Gamma1 (1 : ℕ)).map (mapGL ℝ)) k where
  toFun f :=
    { toFun := f
      slash_action_eq' γ hγ := by
        have hγ' : γ ∈ (Gamma (1 : ℕ)).map (mapGL ℝ) := by
          rw [map_Gamma_one_eq_map_Gamma1_one]; exact hγ
        exact f.slash_action_eq' γ hγ'
      holo' := f.holo'
      zero_at_cusps' {c} hc := by
        have hc' : IsCusp c ((Gamma (1 : ℕ)).map (mapGL ℝ)) := by
          rw [map_Gamma_one_eq_map_Gamma1_one]; exact hc
        exact f.zero_at_cusps' hc' }
  invFun f :=
    { toFun := f
      slash_action_eq' γ hγ := by
        have hγ' : γ ∈ (Gamma1 (1 : ℕ)).map (mapGL ℝ) := by
          rw [← map_Gamma_one_eq_map_Gamma1_one]; exact hγ
        exact f.slash_action_eq' γ hγ'
      holo' := f.holo'
      zero_at_cusps' {c} hc := by
        have hc' : IsCusp c ((Gamma1 (1 : ℕ)).map (mapGL ℝ)) := by
          rw [← map_Gamma_one_eq_map_Gamma1_one]; exact hc
        exact f.zero_at_cusps' hc' }
  left_inv f := by ext z; rfl
  right_inv f := by ext z; rfl
  map_add' f g := by ext z; rfl
  map_smul' c f := by ext z; rfl

/-- The dimension of `S_12(Γ₁(1))` is 1. Inherited from
`Module.finrank ℂ (CuspForm Γ(1) 12) = 1` (which holds via the iso with `M_0(Γ(1))`). -/
lemma finrank_cuspForm_lvl1_weight12 :
    Module.finrank ℂ
      (CuspForm ((Gamma1 (1 : ℕ)).map (mapGL ℝ)) 12) = 1 := by
  have h1 : Module.finrank ℂ (CuspForm (CongruenceSubgroup.Gamma 1) 12) = 1 := by
    apply Module.finrank_eq_of_rank_eq
    rw [LinearEquiv.rank_eq (CuspForms_iso_Modforms 12)]
    simp
    exact ModularForm.levelOne_weight_zero_rank_one
  rw [← LinearEquiv.finrank_eq (cuspForm_Gamma_one_equiv_Gamma1_one 12)]
  exact h1

/-- **The discriminant `Delta` is a Hecke eigenform**: for every `n : ℕ+`,
the Hecke operator `T_n` maps `Delta` to a scalar multiple of `Delta`.

The proof is a dimension argument: since `dim S_12(Γ₁(1)) = 1` and `Delta ≠ 0`,
every cusp form in `S_12(Γ₁(1))` is a scalar multiple of `Delta`. In particular,
`heckeT_n_cusp 12 n Delta` is a scalar multiple of `Delta`. -/
theorem Delta_lvl1_isEigenform : IsEigenform (N := 1) (k := 12) Delta_lvl1 := by
  -- For every n, define the eigenvalue as the scalar from the 1-dim space
  classical
  refine ⟨fun n => ?_, fun n _ => ?_⟩
  · -- Define eigenvalue: the scalar c with heckeT_n_cusp 12 n.val Delta_lvl1 = c • Delta_lvl1
    haveI : NeZero n.val := ⟨n.pos.ne'⟩
    exact (finrank_eq_one_iff_of_nonzero' Delta_lvl1 Delta_lvl1_ne_zero).mp
      finrank_cuspForm_lvl1_weight12 (heckeT_n_cusp 12 n.val Delta_lvl1) |>.choose
  · -- Show the chosen scalar works
    haveI : NeZero n.val := ⟨n.pos.ne'⟩
    have h := ((finrank_eq_one_iff_of_nonzero' Delta_lvl1 Delta_lvl1_ne_zero).mp
      finrank_cuspForm_lvl1_weight12 (heckeT_n_cusp 12 n.val Delta_lvl1)).choose_spec
    exact h.symm

end HeckeRing.GL2
