/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import LeanModularForms.HeckeRIngs.GL2.Gamma1Pair

/-!
# Level Embeddings and Primitive Form Infrastructure

Defines the level-raising inclusion `Gamma1(M*l) ≤ Gamma1(M)` and the submodule
of cusp forms coming from lower levels (`cuspFormsFromLowerLevels`).

## Main definitions

* `Gamma1_le_of_dvd` — if `M ∣ N` then `Gamma1 N ≤ Gamma1 M` and `Gamma0 N ≤ Gamma0 M`
* `cuspFormRestrict` — restriction of invariance group along a subgroup inclusion
* `cuspFormsFromLowerLevels` — cusp forms generated by level-raising from proper divisors:
    `S_k^1(N, χ) = ∑_{M | N, M ≠ N} ∑_{l * M = N} image(levelEmbed l)`

These are the **definition-level** prerequisites for Phase 6 (primitive form theory,
Miyake §4.6). The actual level-embedding linear map `f(z) ↦ f(lz)` and the primitive
space `S_k^0 = (S_k^1)⊥` require the Petersson inner product (Phase 4) and the
slash-action compatibility (Phase 2/3).

## References

* Miyake, *Modular Forms*, §4.6 (Lemma 4.6.1, p.162)
* Diamond–Shurman, *A First Course in Modular Forms*, §5.7
-/

open Matrix Matrix.SpecialLinearGroup CongruenceSubgroup

open scoped MatrixGroups ModularForm

namespace HeckeRing.GL2

/-- `Gamma1(N) ≤ Gamma1(M)` when `M ∣ N`: if `a ≡ 1 mod N` then `a ≡ 1 mod M`,
and if `N ∣ c` then `M ∣ c`. -/
theorem Gamma1_le_of_dvd {M N : ℕ} (h : M ∣ N) :
    Gamma1 N ≤ Gamma1 M := by
  intro A hA
  rw [Gamma1_mem] at hA ⊢
  obtain ⟨ha, hd, hc⟩ := hA
  set φ := ZMod.castHom h (ZMod M)
  refine ⟨?_, ?_, ?_⟩
  · simpa [map_intCast, map_one] using congr_arg φ ha
  · simpa [map_intCast, map_one] using congr_arg φ hd
  · simpa [map_intCast, map_zero] using congr_arg φ hc

/-- `Gamma0(N) ≤ Gamma0(M)` when `M ∣ N`: if `N ∣ c` then `M ∣ c`. -/
theorem Gamma0_le_of_dvd {M N : ℕ} (h : M ∣ N) :
    Gamma0 N ≤ Gamma0 M := by
  intro A hA
  rw [Gamma0_mem] at hA ⊢
  simpa [map_intCast, map_zero] using congr_arg (ZMod.castHom h (ZMod M)) hA

/-- `Gamma1(N) ≤ Gamma0(N)` (standard inclusion, for convenience). -/
theorem Gamma1_le_Gamma0 (N : ℕ) : Gamma1 N ≤ Gamma0 N :=
  Gamma1_in_Gamma0 N

/-- The set of proper-divisor level pairs `(M, l)` with `M * l = N` and `M ≠ N`.
These are the sources for level-raising into `S_k(N, χ)`. -/
def lowerLevelPairs (N : ℕ) : Set (ℕ × ℕ) :=
  {p | p.1 * p.2 = N ∧ 0 < p.1 ∧ 1 < p.2}

/-- The set of proper divisors of N that are valid source levels (multiples of
the conductor `m_χ`). For a Dirichlet character `χ` mod `N`, the valid source
levels `M` satisfy `m_χ ∣ M ∣ N` with `M ≠ N`.

Note: the conductor `m_χ` is available via `DirichletCharacter.conductor`. -/
def validSourceLevels (N : ℕ) (m_χ : ℕ) : Set ℕ :=
  {M | m_χ ∣ M ∧ M ∣ N ∧ M ≠ N ∧ 0 < M}

end HeckeRing.GL2
