/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: LeanModularForms contributors
-/
import LeanModularForms.HeckeRIngs.GL2.Unified.Gamma0Trivial
import LeanModularForms.HeckeRIngs.GL2.Unified.CuspNebentypusSpace

/-!
# Commutative good-index Hecke rings

This file turns any `GoodHeckeFamily` into an actual commutative subalgebra of
the endomorphism ring, generated by the away-from-level operators themselves.

For the current experimental unification layer, this gives a common ring-shaped
proof source for commutativity on:

* `Γ₁(N)` character spaces
* transported `Γ₀(N), χ`-style modular-form spaces
* cusp-form character spaces
* transported `Γ₀(N), χ`-style cusp spaces
* the trivial-character `Γ₀(N)` and level-1 specializations

The direct twisted `Γ₀(N),χ` Hecke-ring action now lives in
`Unified.TwistedHeckeRing`. This file remains the smaller public
`GoodHeckeFamily` subalgebra interface for the existing concrete good-index
operators.
-/

open scoped MatrixGroups ModularForm

namespace HeckeRing.GL2.Unified

variable {N : ℕ} [NeZero N]

namespace GoodHeckeFamily

variable {V : Type*} [AddCommGroup V] [Module ℂ V]

/-- The commutative subalgebra generated by the good-index Hecke operators of a
`GoodHeckeFamily`. -/
noncomputable def heckeSubalgebra (F : GoodHeckeFamily N V) : Subalgebra ℂ (Module.End ℂ V) :=
  Algebra.adjoin ℂ (Set.range F.op)

@[simp] lemma op_mem_heckeSubalgebra (F : GoodHeckeFamily N V) (n : GoodIndex N) :
    F.op n ∈ F.heckeSubalgebra :=
  Algebra.subset_adjoin ⟨n, rfl⟩

/-- The good-index Hecke subalgebra is commutative because its generators
already commute pairwise. -/
noncomputable instance instCommRingHeckeSubalgebra (F : GoodHeckeFamily N V) :
    CommRing F.heckeSubalgebra :=
  Algebra.adjoinCommRingOfComm (R := ℂ) (s := Set.range F.op) <| by
    rintro _ ⟨m, rfl⟩ _ ⟨n, rfl⟩
    exact (F.commute m n).eq

/-- Any two endomorphisms lying in the good-index Hecke subalgebra commute,
because the subalgebra itself is commutative. -/
lemma commute_of_mem_heckeSubalgebra (F : GoodHeckeFamily N V) {x y : Module.End ℂ V}
    (hx : x ∈ F.heckeSubalgebra) (hy : y ∈ F.heckeSubalgebra) : Commute x y :=
  congrArg Subtype.val (mul_comm (⟨x, hx⟩ : F.heckeSubalgebra) ⟨y, hy⟩)

/-- The defining Hecke operators commute because they lie in the good-index
Hecke subalgebra. -/
theorem commute_from_heckeSubalgebra (F : GoodHeckeFamily N V) (m n : GoodIndex N) :
    Commute (F.op m) (F.op n) :=
  F.commute_of_mem_heckeSubalgebra (F.op_mem_heckeSubalgebra m) (F.op_mem_heckeSubalgebra n)

/-- Pointwise form of `commute_from_heckeSubalgebra`. -/
theorem commute_apply_from_heckeSubalgebra (F : GoodHeckeFamily N V) (m n : GoodIndex N) (v : V) :
    F.op m (F.op n v) = F.op n (F.op m v) :=
  LinearMap.congr_fun (F.commute_from_heckeSubalgebra m n).eq v

end GoodHeckeFamily

section Modular

open HeckeRing.GL2

/-- In the experimental `Γ₁(N), χ` modular family, commutativity is now a
corollary of the commutative good-index Hecke subalgebra. -/
theorem modFormCharSpaceFamily_commute_from_heckeRing (k : ℤ) (χ : (ZMod N)ˣ →* ℂˣ)
    (m n : GoodIndex N) :
    Commute ((modFormCharSpaceFamily (N := N) k χ).op m)
      ((modFormCharSpaceFamily (N := N) k χ).op n) :=
  (modFormCharSpaceFamily (N := N) k χ).commute_from_heckeSubalgebra m n

/-- Pointwise form of `modFormCharSpaceFamily_commute_from_heckeRing`. -/
theorem modFormCharSpaceFamily_commute_apply_from_heckeRing (k : ℤ) (χ : (ZMod N)ˣ →* ℂˣ)
    (m n : GoodIndex N) (f : modFormCharSpace k χ) :
    (modFormCharSpaceFamily (N := N) k χ).op m
        ((modFormCharSpaceFamily (N := N) k χ).op n f) =
      (modFormCharSpaceFamily (N := N) k χ).op n
        ((modFormCharSpaceFamily (N := N) k χ).op m f) :=
  (modFormCharSpaceFamily (N := N) k χ).commute_apply_from_heckeSubalgebra m n f

/-- In the transported experimental `Γ₀(N), χ` modular family, commutativity is
also a ring-theoretic corollary of the same construction. -/
theorem gamma0NebentypusFamily_commute_from_heckeRing (k : ℤ) (χ : (ZMod N)ˣ →* ℂˣ)
    (m n : GoodIndex N) :
    Commute ((gamma0NebentypusFamily (N := N) k χ).op m)
      ((gamma0NebentypusFamily (N := N) k χ).op n) :=
  (gamma0NebentypusFamily (N := N) k χ).commute_from_heckeSubalgebra m n

/-- Trivial-character `Γ₀(N)` modular commutativity from the experimental
good-index Hecke ring. -/
theorem gamma0TrivialFamily_commute_from_heckeRing (k : ℤ) (m n : GoodIndex N) :
    Commute ((gamma0TrivialFamily (N := N) k).op m) ((gamma0TrivialFamily (N := N) k).op n) :=
  (gamma0TrivialFamily (N := N) k).commute_from_heckeSubalgebra m n

/-- Level-1 modular commutativity from the same ring-shaped source. -/
theorem levelOneFamily_commute_from_heckeRing (k : ℤ) (m n : GoodIndex 1) :
    Commute ((levelOneFamily k).op m) ((levelOneFamily k).op n) :=
  (levelOneFamily k).commute_from_heckeSubalgebra m n

end Modular

section Cusp

open HeckeRing.GL2

/-- In the experimental cusp `Γ₁(N), χ` family, commutativity is a corollary of
the commutative good-index Hecke subalgebra. -/
theorem cuspFormCharSpaceFamily_commute_from_heckeRing (k : ℤ) (χ : (ZMod N)ˣ →* ℂˣ)
    (m n : GoodIndex N) :
    Commute ((cuspFormCharSpaceFamily (N := N) k χ).op m)
      ((cuspFormCharSpaceFamily (N := N) k χ).op n) :=
  (cuspFormCharSpaceFamily (N := N) k χ).commute_from_heckeSubalgebra m n

/-- Pointwise form of `cuspFormCharSpaceFamily_commute_from_heckeRing`. -/
theorem cuspFormCharSpaceFamily_commute_apply_from_heckeRing (k : ℤ) (χ : (ZMod N)ˣ →* ℂˣ)
    (m n : GoodIndex N) (f : cuspFormCharSpace k χ) :
    (cuspFormCharSpaceFamily (N := N) k χ).op m
        ((cuspFormCharSpaceFamily (N := N) k χ).op n f) =
      (cuspFormCharSpaceFamily (N := N) k χ).op n
        ((cuspFormCharSpaceFamily (N := N) k χ).op m f) :=
  (cuspFormCharSpaceFamily (N := N) k χ).commute_apply_from_heckeSubalgebra m n f

/-- In the transported experimental cusp `Γ₀(N), χ` family, commutativity is
also a ring-theoretic corollary. -/
theorem cuspGamma0NebentypusFamily_commute_from_heckeRing (k : ℤ) (χ : (ZMod N)ˣ →* ℂˣ)
    (m n : GoodIndex N) :
    Commute ((cuspGamma0NebentypusFamily (N := N) k χ).op m)
      ((cuspGamma0NebentypusFamily (N := N) k χ).op n) :=
  (cuspGamma0NebentypusFamily (N := N) k χ).commute_from_heckeSubalgebra m n

end Cusp

end HeckeRing.GL2.Unified
