/-
Copyright (c) 2024 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import LeanModularForms.HeckeRIngs.GLn.CoprimeMul
import Mathlib.Data.Nat.Factorization.Basic
import Mathlib.Data.Nat.GCD.BigOperators

/-!
# Prime Decomposition of Hecke Ring Elements

p-adic decomposition of diagonal Hecke operators and the p-local Hecke subring R_p.
Every `T(a₁,...,aₙ)` factors into a product of p-power `T`-elements via coprime splitting.

## Main definitions

* `ppowDiag` — p-power diagonal: entries are `p^(e i)`
* `pComponent` — extract the p-adic valuation of each diagonal entry
* `removePrime` — remove the p-component from a diagonal (p-free part)
* `R_p` — the p-local Hecke subring generated by p-power T-elements

## Main results

* `divChain_ppow` — monotone exponents give a divisibility chain for p-power diagonals
* `T_elem_split_prime` — binary prime splitting: `T(a) = T(p-part) · T(p-free part)`
* `T_elem_ppow_mem_R_p` — p-power T-elements lie in R_p
* `T_elem_mem_closure_ppow` — every T-element is in the subring generated by all p-local pieces

## References

* Shimura, *Introduction to the Arithmetic Theory of Automorphic Functions*, §3.2
-/

open Matrix Subgroup.Commensurable Pointwise HeckeRing DoubleCoset

open scoped Pointwise

namespace HeckeRing.GLn

variable (n : ℕ)

section PPow

/-- p-power diagonal: entries are `p^(e i)`. -/
def ppowDiag (p : ℕ) (e : Fin n → ℕ) : Fin n → ℕ :=
  fun i ↦ p ^ e i

lemma ppowDiag_pos (p : ℕ) (hp : p.Prime) (e : Fin n → ℕ) :
    ∀ i, 0 < ppowDiag n p e i :=
  fun _ ↦ pow_pos hp.pos _

/-- DivChain for p-power diagonals when exponents are monotone. -/
lemma divChain_ppow (p : ℕ) (e : Fin n → ℕ) (hmono : Monotone e) :
    DivChain n (ppowDiag n p e) := fun _ _ ↦
  Nat.pow_dvd_pow p (hmono (Fin.mk_le_mk.mpr (by omega)))

/-- Extract the p-component of each entry in a positive diagonal. -/
def pComponent (p : ℕ) (a : Fin n → ℕ) : Fin n → ℕ :=
  fun i ↦ (a i).factorization p

/-- The p-component of a divisibility chain is monotone. -/
lemma pComponent_monotone (a : Fin n → ℕ)
    (ha_pos : ∀ i, 0 < a i) (ha : DivChain n a) (p : ℕ) :
    Monotone (pComponent n p a) := fun i j hij ↦
  (Nat.factorization_le_iff_dvd (ha_pos i).ne' (ha_pos j).ne').mpr
    (divChain_dvd (n := n) ha hij) p

end PPow

section RemovePrime

/-- Remove the p-component from each entry: `a_i ↦ a_i / p^{v_p(a_i)}`.
    This is the p-free part (ordCompl) of each diagonal entry. -/
noncomputable def removePrime (p : ℕ) (a : Fin n → ℕ) : Fin n → ℕ :=
  fun i ↦ (a i) / p ^ ((a i).factorization p)

lemma removePrime_pos (p : ℕ) (a : Fin n → ℕ) (ha_pos : ∀ i, 0 < a i) :
    ∀ i, 0 < removePrime n p a i :=
  fun i ↦ Nat.ordCompl_pos p (ha_pos i).ne'

/-- The p-free part preserves divisibility chains. -/
lemma removePrime_divChain (p : ℕ) (a : Fin n → ℕ) (ha : DivChain n a) :
    DivChain n (removePrime n p a) := by
  intro i hi
  obtain ⟨k, hk⟩ := ha i hi
  simp only [removePrime, hk, Nat.ordCompl_mul]
  exact dvd_mul_right _ _

/-- Recovery: the pointwise product of p-part and p-free part equals the original. -/
lemma mul_ppow_remove_eq (p : ℕ) (a : Fin n → ℕ) :
    ppowDiag n p (pComponent n p a) * removePrime n p a = a :=
  funext fun i ↦ Nat.ordProj_mul_ordCompl_eq_self (a i) p

end RemovePrime

section Coprimality

/-- The determinant of a p-power diagonal is a power of `p`. -/
lemma prod_ppow (p : ℕ) (e : Fin n → ℕ) :
    ∏ i, (ppowDiag n p e) i = p ^ (∑ i, e i) := by
  simp [ppowDiag, Finset.prod_pow_eq_pow_sum]

/-- The p-part and p-free part determinants are coprime. -/
lemma prod_ppow_remove_coprime (p : ℕ) (hp : p.Prime)
    (a : Fin n → ℕ) (ha_pos : ∀ i, 0 < a i) :
    Nat.Coprime (∏ i, (ppowDiag n p (pComponent n p a) i))
               (∏ i, (removePrime n p a) i) := by
  rw [prod_ppow]
  exact (Nat.Coprime.prod_right fun i _ ↦ Nat.coprime_ordCompl hp (ha_pos i).ne').pow_left _

end Coprimality

variable [NeZero n]

section Splitting

/-- T_elem is determined by its diagonal, independent of the positivity/DivChain proofs. -/
lemma T_elem_congr_diag {a b : Fin n → ℕ} (h : a = b) : T_elem a = T_elem b := h ▸ rfl

/-- Binary prime splitting: `T(a) = T(p-part) · T(p-free part)`.
    Every diagonal Hecke element factors into its p-power component
    and its p-free component, for any prime `p`. -/
theorem T_elem_split_prime (a : Fin n → ℕ) (ha_pos : ∀ i, 0 < a i)
    (ha : DivChain n a) (p : ℕ) (hp : p.Prime) :
    T_elem a =
    T_elem (ppowDiag n p (pComponent n p a)) *
    T_elem (removePrime n p a) := by
  rw [T_elem_congr_diag n (mul_ppow_remove_eq n p a).symm]
  exact (T_diag_mul_coprime n _ _ (ppowDiag_pos n p hp _) (removePrime_pos n p a ha_pos)
    (divChain_ppow n p _ (pComponent_monotone n a ha_pos ha p))
    (removePrime_divChain n p a ha) (prod_ppow_remove_coprime n p hp a ha_pos)).symm

end Splitting

section RpSubring

/-- The p-local Hecke ring: subring generated by `T_elem` with p-power entries.
    This is Shimura's `R_p^{(n)}`. -/
noncomputable def R_p (p : ℕ) (_hp : p.Prime) : Subring (HeckeAlgebra n) :=
  Subring.closure { f | ∃ (e : Fin n → ℕ) (_hmono : Monotone e),
    f = T_elem (ppowDiag n p e) }

/-- A T_elem with p-power entries lies in R_p. -/
lemma T_elem_ppow_mem_R_p (p : ℕ) (hp : p.Prime) (e : Fin n → ℕ) (hmono : Monotone e) :
    T_elem (ppowDiag n p e) ∈ R_p n p hp :=
  Subring.subset_closure ⟨e, hmono, rfl⟩

end RpSubring

section Generation

end Generation

end HeckeRing.GLn
