import Verso
import VersoManual
import VersoBlueprint
import LeanModularForms.HeckeRIngs.GLn.PrimeDecomposition
import LeanModularForms.HeckeRIngs.GLn.PolynomialRing

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "The p-local Hecke ring as a polynomial ring (Shimura 3.20)" =>

Fix a prime $`p`. Inside the $`\mathrm{GL}_n` Hecke algebra sits the subring $`R_p` generated by
the double cosets whose elementary divisors are all powers of $`p`. Shimura's Theorem 3.20
\[Sh, §3.2\] identifies this *p-local Hecke ring* with a polynomial ring over $`\mathbb{Z}` in the
$`n` generators $`T(1,\dots,1,p,\dots,p)`. This chapter records the p-local subring itself, its
distinguished generators, the evaluation homomorphism out of the multivariate polynomial ring, and
the resulting isomorphism.

:::definition "R-p" (lean := "HeckeRing.GLn.R_p")
*The p-local Hecke ring.*
Fix a prime $`p`. The *p-local Hecke ring* $`R_p` is the subring of the $`\mathrm{GL}_n` Hecke
algebra generated by the diagonal basis elements whose elementary divisors are powers of $`p`.
Concretely, for a tuple of exponents $`e=(e_1,\dots,e_n)` write
$$`
  \operatorname{diag}(p^{e_1},\dots,p^{e_n})
`
for the associated p-power diagonal; when the exponents are non-decreasing,
$`e_1\le\dots\le e_n`, this matrix has determinant $`p^{e_1+\dots+e_n}` and its successive
entries form a divisibility chain $`p^{e_1}\mid\dots\mid p^{e_n}`, so it is a valid diagonal
representative and gives a diagonal basis element of the Hecke algebra. The ring $`R_p` is the
subring generated by all such basis elements as $`e` ranges over non-decreasing exponent tuples;
it is Shimura's $`R_p^{(n)}`.

Depends on: {uses "hecke-algebra"}[]
:::

:::definition "T-gen" (lean := "HeckeRing.GLn.T_gen")
*The distinguished generators of $`R_p`.*
Fix a prime $`p`. For each index $`k=1,\dots,n` the $`k`-th generator is the double-coset class
$$`
  T_k = T(\underbrace{1,\dots,1}_{n-k},\underbrace{p,\dots,p}_{k}),
`
the diagonal basis element attached to $`\operatorname{diag}(p^{e_1},\dots,p^{e_n})` whose first
$`n-k` exponents are $`0` and whose last $`k` exponents are $`1`. Equivalently $`T_k` is the class of
the diagonal matrix with its first $`n-k` entries equal to $`1` and its last $`k` entries equal to
$`p`. These exponents are non-decreasing, so each $`T_k` is a genuine diagonal basis element lying in
the $`p`-local Hecke ring; the extreme cases are $`T_1 = T(1,\dots,1,p)` and $`T_n = T(p,\dots,p)`.
The $`n` classes $`T_1,\dots,T_n` are Shimura's distinguished generators, and they generate $`R_p`
\[Sh, §3.2\].

Depends on: {uses "R-p"}[] {uses "hecke-algebra"}[]
:::

:::definition "evalHom" (lean := "HeckeRing.GLn.evalHom")
*Evaluation of polynomials at the distinguished generators.*
Fix a prime $`p`. The *evaluation homomorphism* is the ring homomorphism
$$`
  \mathbb{Z}[X_1,\dots,X_n]\longrightarrow\mathcal{H}_n,\qquad X_k\longmapsto T_k,
`
from the polynomial ring in $`n` variables over $`\mathbb{Z}` into the $`\mathrm{GL}_n` Hecke
algebra $`\mathcal{H}_n`, defined by sending each variable $`X_k` to the $`k`-th distinguished
generator $`T_k` and each integer to the corresponding integer multiple of the identity. A monomial
$`X_1^{a_1}\cdots X_n^{a_n}` is thus sent to the product $`T_1^{a_1}\cdots T_n^{a_n}`, and an
arbitrary polynomial to the corresponding integer combination of such products. For this assignment
to extend to a *ring* homomorphism it is essential that the Hecke algebra be *commutative*: the
universal property of the polynomial ring produces a homomorphism out of $`\mathbb{Z}[X_1,\dots,X_n]`
exactly because the images $`T_1,\dots,T_n` of the variables commute with one another in the target.
Since every generator $`T_k` lies in the $`p`-local subring $`R_p`, the image of the evaluation
homomorphism is contained in $`R_p`; this map is the candidate inverse to the coordinate description
of $`R_p`, and Shimura's Theorem 3.20 \[Sh, §3.2\] asserts that it restricts to an isomorphism onto
$`R_p`.

Depends on: {uses "T-gen"}[] {uses "commring-hecke-algebra"}[]
:::

:::theorem "T-gen-generates-R-p" (lean := "HeckeRing.GLn.Surj.T_gen_generates_R_p_two")
*Surjectivity of evaluation at $`n=2` (one half of Shimura 3.20).*
Take $`n=2` and fix a prime $`p`. Then every element of the $`p`-local Hecke ring $`R_p` lies in the
image of the evaluation homomorphism; that is, each element of $`R_p` is a polynomial with integer
coefficients in the two distinguished generators
$$`
  T_1 = T(1,p), \qquad T_2 = T(p,p).
`
Concretely, for every $`f\in R_p` there is a polynomial $`P\in\mathbb{Z}[X_1,X_2]` with
$`f = P(T_1,T_2)`, so the evaluation homomorphism $`\mathbb{Z}[X_1,X_2]\to\mathcal{H}_2` has the
whole of $`R_p` inside its range.

Depends on: {uses "T-gen"}[] {uses "R-p"}[] {uses "evalHom"}[]
:::

:::proof "T-gen-generates-R-p"
Since $`R_p` is by definition the subring generated by the diagonal basis classes
$`T(p^{a},p^{b})` with $`a\le b`, it suffices to write each such generator as a polynomial in
$`T_1` and $`T_2`; the polynomials in the range then close up under the ring operations to cover all
of $`R_p`. Factor a generator $`T(p^{a},p^{b})` with $`a\le b` through the scalar class: pulling out
$`a` copies of $`T_2=T(p,p)` shifts both elementary divisors down by $`a`, so
$`T(p^{a},p^{b}) = T_2^{\,a}\,T(1,p^{b-a})`. Because the scalar powers satisfy
$`T(p^{a},p^{a}) = T_2^{\,a}`, it remains only to express the *primitive* classes $`T(1,p^{k})` as
polynomials in $`T_1` and $`T_2`. (In particular every purely scalar class $`T(p^{a},p^{a})` is just
the power $`T_2^{\,a}`.)

The classes $`T(1,p^{k})` are handled by a double induction running through the prime-power sums
$`T(p^{k})`. For the sums, $`T(p^{0})=1` and $`T(p)=T(1,p)=T_1` are immediate, while for $`k\ge 2`
the prime-power recurrence {bpref "T-sum-ppow-recurrence"}[],
$$`
  T(p^{k}) \;=\; T_1\,T(p^{k-1}) \;-\; p\,\bigl(T_2\,T(p^{k-2})\bigr),
`
expresses $`T(p^{k})` from the two preceding sums together with $`T_1` and $`T_2`; by strong
induction every $`T(p^{k})` is therefore a polynomial in the two generators. The primitive classes
then follow from the telescoping relation {bpref "T-ad-one-ppow-eq"}[]: one has
$`T(1,p^{0})=1` and $`T(1,p)=T_1`, and for $`k\ge 2`
$$`
  T(1,p^{k}) \;=\; T(p^{k}) \;-\; T_2\,T(p^{k-2}),
`
which is again a polynomial in $`T_1` and $`T_2`. Substituting back into the factorisation
$`T(p^{a},p^{b}) = T_2^{\,a}\,T(1,p^{b-a})` exhibits every diagonal generator of $`R_p`, and hence
every element of $`R_p`, as a polynomial in $`T_1` and $`T_2`.

Uses: {uses "T-sum-ppow-recurrence"}[] {uses "T-ad-one-ppow-eq"}[]
:::

:::theorem "R-p-isPolynomialRing" (lean := "HeckeRing.GLn.R_p_isPolynomialRing")
*Shimura's Theorem 3.20: the p-local Hecke ring is a polynomial ring.*
Fix a prime $`p`. The evaluation homomorphism, corestricted to its image, is a ring isomorphism
$$`
  \mathbb{Z}[X_1,\dots,X_n]\;\xrightarrow{\ \sim\ }\;R_p,\qquad X_k\longmapsto T_k,
`
between the polynomial ring in $`n` variables over $`\mathbb{Z}` and the $`p`-local Hecke ring
$`R_p`. Equivalently, the corestricted evaluation map $`\mathbb{Z}[X_1,\dots,X_n]\to R_p` sending each
variable $`X_k` to the $`k`-th distinguished generator $`T_k` is a bijection: it is surjective onto
$`R_p` and injective. Thus $`R_p` is freely generated as a commutative ring over $`\mathbb{Z}` by the
$`n` classes $`T_1,\dots,T_n`, which are consequently algebraically independent; there is no
polynomial relation among the $`T_k` beyond those forced by the ring axioms, and every element of
$`R_p` is uniquely a polynomial with integer coefficients in $`T_1,\dots,T_n` \[Sh, Thm 3.20\].

Depends on: {uses "evalHom"}[] {uses "T-gen-generates-R-p"}[] {uses "R-p"}[]
:::

:::proof "R-p-isPolynomialRing"
The corestricted evaluation map is a ring homomorphism with the right source and target, so it
remains to prove that it is bijective. Surjectivity onto $`R_p` is precisely
{bpref "T-gen-generates-R-p"}[]: every element of $`R_p` is a polynomial with integer coefficients in
the distinguished generators, so the whole of $`R_p` lies in the image. It therefore suffices to
establish injectivity, which is the algebraic-independence half of the statement: a polynomial mapping
to $`0` must already be the zero polynomial.

Injectivity is proved by a leading-term argument that separates distinct monomials by evaluating the
resulting Hecke operator at a carefully chosen diagonal double coset. Suppose a nonzero polynomial $`R`
lay in the kernel. Among the monomials appearing in $`R`, choose one whose final exponent is minimal,
say the monomial with exponent tuple $`s=(s_1,\dots,s_n)`, and consider the $`p`-power diagonal coset
$`T(p^{s_1},\dots)` built from $`s` (in the rank-two case the coset $`T(p^{s_2},p^{s_1+s_2})` attached
to $`s`). The image of $`R` is a finite integer combination of products of generators, and evaluating
that combination at this coset isolates a single monomial: the chosen monomial contributes its own
coefficient, while every other monomial contributes $`0`. The vanishing of the off-diagonal terms is
exactly a Kronecker-delta property of the generators — a product $`T_1^{a_1}\cdots T_n^{a_n}`,
evaluated at the diagonal coset attached to $`s`, equals $`1` when its exponents match $`s` and $`0`
otherwise. Monomials whose final exponent strictly exceeds that of $`s` vanish because the
corresponding scalar power $`p^{a_n}` fails to divide the relevant elementary divisor, while a monomial
sharing the minimal final exponent but differing elsewhere is killed by the matching condition; the
minimality of $`s` is what guarantees that no surviving monomial can overshoot. Since the image of
$`R` is $`0`, this evaluation reads off the coefficient of the chosen monomial as $`0`, contradicting
its presence in the support. Hence the kernel is trivial and the corestricted evaluation map is a
bijection, giving the ring isomorphism $`\mathbb{Z}[X_1,\dots,X_n]\simeq R_p` of \[Sh, Thm 3.20\].

Uses: {uses "T-gen-generates-R-p"}[] {uses "evalHom"}[] {uses "R-p"}[]
:::
