import Verso
import VersoManual
import VersoBlueprint
import LeanModularForms.HeckeRIngs.GL2.Gamma1Pair
import LeanModularForms.HeckeRIngs.GL2.Newforms.Basic
import LeanModularForms.HeckeRIngs.GL2.Newforms.CoeffSeq
import LeanModularForms.HeckeRIngs.GL2.Newforms.MainLemma
import LeanModularForms.HeckeRIngs.GL2.Unified.EigenformFromRing
import LeanModularForms.SMOObligations.StrongMultiplicityOneFull

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "Strong Multiplicity One" =>

This is the headline chapter. Strong Multiplicity One \[Miy, Thm 4.6.12\] (equivalently \[DS, Thm 5.8.2\])
says that a Hecke eigenform is rigidly determined by its eigenvalues at almost all primes: if a
normalised newform $`f` in $`S_k(N,\chi)` and any cusp-form Hecke eigenfunction $`g` in $`S_k(N,\chi)`
share the eigenvalues $`\lambda_n` for all $`n` with $`(n,N)=1` outside a finite set, then $`g=c\,f` for a
single constant $`c\in\mathbb{C}`. The result rests squarely on the commutativity of the $`\mathrm{GL}_2`
Hecke algebra established in the previous chapters ({bpref "commring-hecke-algebra"}[]) together
with its multiplication table ({bpref "T-sum-mul"}[]): commutativity is what makes simultaneous
diagonalisation possible, and the rigidity of the eigenvalue systems is read off from the structure of
the $`T(n)`. The proof decomposes $`g` along the Petersson-orthogonal new/old splitting, shows the new
part is a multiple of $`f`, and shows the old part vanishes.

:::definition "modFormCharSpace" (lean := "HeckeRing.GL2.modFormCharSpace")
*Nebentypus space $`S_k(N,\chi)`.*
For a positive integer $`N`, a weight $`k`, and a Dirichlet character $`\chi` modulo $`N`, the
*Nebentypus space* (modular-form version $`M_k(N,\chi)`, cusp version $`S_k(N,\chi)`) is the
common eigenspace
$$`
  M_k(N,\chi) \;=\; \bigcap_{d} \ker\bigl(\langle d\rangle - \chi(d)\bigr),
`
the intersection over all units $`d` modulo $`N` of the $`\chi(d)`-eigenspaces of the diamond operators
$`\langle d\rangle`. Equivalently, $`f` lies in $`M_k(N,\chi)` if and only if $`\langle d\rangle f=\chi(d)\,f`
for every $`d` coprime to $`N`.
:::

:::definition "eigenform" (lean := "HeckeRing.GL2.Eigenform")
*Eigenform.*
An *eigenform* of level $`\Gamma_1(N)` and weight $`k` is a cusp form $`f` carrying a Nebentypus
character $`\chi`, so that $`f` lies in the eigenspace $`S_k(N,\chi)`, and which is a simultaneous
eigenfunction of all the Hecke operators $`T(n)` with $`(n,N)=1`. Because the Hecke operators commute
({bpref "commring-hecke-algebra"}[], whose product law is the multiplication table
{bpref "T-sum-mul"}[]), such common eigenfunctions exist in abundance: a finite-dimensional space
of cusp forms is simultaneously diagonalised by the commuting family $`\{T(n)\}_{(n,N)=1}`. The eigenvalue
is recorded as $`T(n)f=\lambda_n\,f`, where $`\lambda_n=\chi(n)\,\nu_n` relates the classical Hecke
eigenvalue $`\lambda_n` to the underlying Hecke-ring eigenvalue $`\nu_n` through the diamond factor $`\chi(n)`.

Depends on: {uses "modFormCharSpace"}[]
:::

:::definition "cuspFormsOld" (lean := "HeckeRing.GL2.cuspFormsOld")
*Old subspace $`S_k^{\flat}(N)`.*
The *old subspace* $`S_k^{\flat}(N)` is the span of all level-raising images: for each proper divisor
$`M\mid N` (with $`M\neq N`) and each divisor $`\ell` of $`N/M` with $`\ell>1`, the degeneracy map
$`f\mapsto f(\ell z)` carries the cusp space at level $`M` into level $`N`, and $`S_k^{\flat}(N)` is the
subspace generated by all such images,
$$`
  S_k^{\flat}(N) \;=\; \operatorname{span}\bigl\{\, f(\ell z) \ :\ f\in S_k(\Gamma_1(M)),\ M\mid N,\ M\neq N \,\bigr\}.
`
This is the \[DS, (5.18)\] definition of the forms “coming from lower level”.
:::

:::definition "cuspFormsNew" (lean := "HeckeRing.GL2.cuspFormsNew")
*New subspace $`S_k^{\sharp}(N)`.*
The *new subspace* $`S_k^{\sharp}(N)` is the orthogonal complement of the old subspace
$`S_k^{\flat}(N)` inside $`S_k(\Gamma_1(N))` with respect to the Petersson inner product,
$$`
  S_k^{\sharp}(N) \;=\; \bigl(S_k^{\flat}(N)\bigr)^{\perp},
`
following \[DS, (5.19)\]. Concretely, a cusp form lies in $`S_k^{\sharp}(N)` exactly when it is Petersson-orthogonal
to every oldform. The Petersson form is positive definite on cusp forms, so $`S_k^{\sharp}(N)\cap S_k^{\flat}(N)=0`.

Depends on: {uses "cuspFormsOld"}[]
:::

:::definition "oldPart" (lean := "HeckeRing.GL2.oldPart")
*Old part.*
Since $`S_k(\Gamma_1(N))=S_k^{\flat}(N)\oplus S_k^{\sharp}(N)` as an orthogonal direct sum, every cusp form
$`f` has a unique decomposition into an old and a new component. The *old part* of $`f` is its image
under the projection of $`S_k(\Gamma_1(N))` onto $`S_k^{\flat}(N)` along $`S_k^{\sharp}(N)`.

Depends on: {uses "cuspFormsOld"}[] {uses "cuspFormsNew"}[]
:::

:::definition "newPart" (lean := "HeckeRing.GL2.newPart")
*New part.*
The *new part* of a cusp form $`f` is its image under the projection of $`S_k(\Gamma_1(N))` onto the
new subspace $`S_k^{\sharp}(N)` along the old subspace $`S_k^{\flat}(N)`. Together with the old part it
recovers $`f`: one has $`f=\operatorname{old}(f)+\operatorname{new}(f)` with $`\operatorname{old}(f)\in S_k^{\flat}(N)`
and $`\operatorname{new}(f)\in S_k^{\sharp}(N)`.

Depends on: {uses "cuspFormsOld"}[] {uses "cuspFormsNew"}[]
:::

:::definition "newform" (lean := "HeckeRing.GL2.Newform")
*Newform.*
A *newform* (normalised newform) of level $`\Gamma_1(N)` and weight $`k` is an eigenform $`f` that lies
in the new subspace $`S_k^{\sharp}(N)` and is normalised so that its first Fourier coefficient is $`a_1=1`.
By Atkin–Lehner uniqueness \[DS, Thm 5.8.2\] a newform is determined by its Hecke eigenvalues away from the
level; {bpref "smo-clean"}[] below is exactly this rigidity in the present formalisation.

Depends on: {uses "eigenform"}[] {uses "cuspFormsNew"}[]
:::

:::theorem "coeff-eq-a1-lambda" (lean := "HeckeRing.GL2.Eigenform.coeff_eq_coeff_one_mul_eigenvalue")
*Miyake 4.5.15(1): $`a_n=a_1\lambda_n`.*
Let $`g` be an eigenform lying in the Nebentypus space $`S_k(N,\chi)`, and let $`n` be coprime to $`N`. Then
the Fourier coefficients of $`g` satisfy
$$`
  a_n(g) \;=\; a_1(g)\,\lambda_n(g),
`
where $`\lambda_n(g)` is the classical Hecke eigenvalue of $`g` at $`n`.

Depends on: {uses "eigenform"}[] {uses "modFormCharSpace"}[]
:::

:::proof "coeff-eq-a1-lambda"
This is \[Miy, Lemma 4.5.15(1)\] in its un-normalised form. Apply the Hecke operator $`T(n)` to $`g`. On the
one hand the eigenform relation gives $`T(n)g=\lambda_n(g)\,g`, so the first Fourier coefficient of $`T(n)g`
is $`\lambda_n(g)\,a_1(g)`. On the other hand the explicit formula for the Fourier coefficients of $`T(n)g`
expresses $`a_m(T(n)g)` as a sum over the common divisors of $`m` and $`n`; taking $`m=1` and using $`(n,N)=1`
the sum collapses to its single $`d=1` term, which is precisely $`a_n(g)`. Equating the two expressions for
the first coefficient of $`T(n)g` yields $`a_n(g)=a_1(g)\,\lambda_n(g)`.

Uses: {uses "eigenform"}[] {uses "modFormCharSpace"}[]
:::

:::theorem "a1-ne-zero" (lean := "HeckeRing.GL2.coeff_one_ne_zero_of_mem_cuspFormsNew_of_eigen")
*Miyake 4.6.11: $`a_1\neq 0` for new eigenforms.*
Let $`g` be a nonzero eigenform lying in $`S_k(N,\chi)\cap S_k^{\sharp}(N)`, that is, a nonzero common
eigenfunction of the $`T(n)`, $`(n,N)=1`, in the new subspace. Then its leading Fourier coefficient is
nonzero, $`a_1(g)\neq 0`.

Depends on: {uses "eigenform"}[] {uses "cuspFormsNew"}[] {uses "coeff-eq-a1-lambda"}[]
:::

:::proof "a1-ne-zero"
This is \[Miy, Lemma 4.6.11\]. Argue by contraposition: suppose $`a_1(g)=0`. By
{bpref "coeff-eq-a1-lambda"}[] every coprime coefficient then vanishes,
$`a_n(g)=a_1(g)\,\lambda_n(g)=0` for all $`(n,N)=1`, and the zeroth coefficient vanishes because $`g` is
cuspidal. A form whose Fourier coefficients all vanish away from the level necessarily lies in the old
subspace (this is the content of \[Miy, Thm 4.6.8\] in the per-character formulation), so $`g\in S_k^{\flat}(N)`.
But $`g` also lies in the new subspace $`S_k^{\sharp}(N)`, and the Petersson form is positive definite, so
$`S_k^{\flat}(N)\cap S_k^{\sharp}(N)=0` forces $`g=0`, contradicting the hypothesis. Hence $`a_1(g)\neq 0`.

Uses: {uses "eigenform"}[] {uses "cuspFormsNew"}[] {uses "coeff-eq-a1-lambda"}[]
:::

:::theorem "eigenform-decomp" (lean := "HeckeRing.GL2.exists_eigenform_decomposition_mem_cuspFormsNew")
*Eigenform old/new splitting.*
Let $`g` be a cusp form in the new subspace $`S_k^{\sharp}(N)` whose underlying modular form lies in the
Nebentypus space $`S_k(N,\chi)`. Then $`g` is a finite sum of common Hecke eigenforms,
$$`
  g \;=\; \sum_{i} h_i,
`
each summand $`h_i` again lying in $`S_k(N,\chi)\cap S_k^{\sharp}(N)` and being a common eigenfunction of all
$`T(n)` with $`(n,N)=1`.

Depends on: {uses "eigenform"}[] {uses "cuspFormsNew"}[] {uses "oldPart"}[] {uses "newPart"}[]
:::

:::proof "eigenform-decomp"
The new subspace is stable under every Hecke operator $`T(n)` with $`(n,N)=1` (DS Prop 5.6.2), and so is the
Nebentypus eigenspace $`S_k(N,\chi)`. Since the operators $`\{T(n)\}_{(n,N)=1}` form a commuting family of
diagonalisable operators on the finite-dimensional space $`S_k(N,\chi)`
({bpref "commring-hecke-algebra"}[]), the simultaneous spectral decomposition of $`S_k(N,\chi)` into
joint eigenspaces restricts to the invariant subspace $`S_k^{\sharp}(N)\cap S_k(N,\chi)`. Writing $`g` in
this joint eigenbasis exhibits it as a finite sum of common eigenforms, each of which is itself new and of
Nebentypus $`\chi`.

Uses: {uses "eigenform"}[] {uses "cuspFormsNew"}[] {uses "oldPart"}[] {uses "newPart"}[]
:::

:::theorem "newPart-eq-smul" (lean := "HeckeRing.GL2.newPart_eq_smul_of_shared_eigenvalues")
*New part is a multiple of $`f`.*
Let $`f` be a normalised newform in $`S_k(N,\chi)` and let $`g^{(1)}` be a common Hecke eigenfunction in the
new subspace lying in $`S_k(N,\chi)` that shares $`f`'s eigenvalues $`\lambda_n` for all $`(n,N)=1` outside a
finite set $`S`. Then
$$`
  g^{(1)} \;=\; b_1\,f, \qquad b_1=a_1(g^{(1)}).
`

Depends on: {uses "newform"}[] {uses "newPart"}[] {uses "coeff-eq-a1-lambda"}[] {uses "a1-ne-zero"}[] {uses "eigenform-decomp"}[]
:::

:::proof "newPart-eq-smul"
This is the new-part half of \[Miy, Thm 4.6.12\]. If $`g^{(1)}=0` then $`b_1=0` and the identity is trivial,
so assume $`g^{(1)}\neq 0`; then $`b_1\neq 0` by {bpref "a1-ne-zero"}[]. Sharing eigenvalues off the
finite set $`S` in fact forces equality of *all* coprime eigenvalues (a nonzero coprime eigenvalue and
the multiplicativity of the eigenvalue system propagate the agreement to every $`(n,N)=1`). Consider
$`h=b_1^{-1}g^{(1)}-f`. For $`(n,N)=1` its $`n`-th coefficient is
$`b_1^{-1}a_n(g^{(1)})-a_n(f)=\lambda_n-\lambda_n=0`, using {bpref "coeff-eq-a1-lambda"}[] together
with the normalisation $`a_1(f)=1` which gives $`a_n(f)=\lambda_n`. A form with vanishing coprime
coefficients lies in the old subspace by \[Miy, Thm 4.6.8\], so $`h\in S_k^{\flat}(N)`; but $`h` is a
difference of new forms, hence $`h\in S_k^{\sharp}(N)`. Orthogonality of the new and old subspaces forces
$`h=0`, i.e.\ $`b_1^{-1}g^{(1)}=f`, which is the claim.

Uses: {uses "newform"}[] {uses "newPart"}[] {uses "coeff-eq-a1-lambda"}[] {uses "a1-ne-zero"}[] {uses "eigenform-decomp"}[]
:::

:::theorem "oldPart-eq-zero" (lean := "HeckeRing.GL2.oldPart_eq_zero_of_shared_eigenvalues")
*Old part vanishes.*
Let $`f` be a nonzero newform in $`S_k(N,\chi)` and let $`g^{(2)}` be a common Hecke eigenfunction in the
($`\chi`-refined) old subspace, lying in $`S_k(N,\chi)`, that shares $`f`'s eigenvalues $`\lambda_n` for all
$`(n,N)=1` outside a finite set $`S`. Then $`g^{(2)}=0`.

Depends on: {uses "newform"}[] {uses "oldPart"}[] {uses "a1-ne-zero"}[] {uses "eigenform-decomp"}[]
:::

:::proof "oldPart-eq-zero"
This is steps (i)–(ii) of \[Miy, Thm 4.6.12\]. Suppose $`g^{(2)}\neq 0`. By the description of the old
subspace \[Miy, Lemma 4.6.9\] one may write $`g^{(2)}` as a sum of level-raises $`h_v(\ell_v z)` of newforms
$`h_v` at proper divisors $`M_v` of $`N`; by {bpref "eigenform-decomp"}[] the $`h_v` may be taken to be
common eigenforms, and by \[Miy, Lemma 4.6.2\] their level-raises remain eigenforms with the same eigenvalues.
Eigenfunctions with distinct eigenvalues are Petersson-orthogonal, hence linearly independent, so the
components whose eigenvalues differ from those of $`f` contribute nothing; removing them leaves a nonzero
new eigenform $`h` at a proper divisor $`M` whose eigenvalues match $`f`'s off $`S`. By
{bpref "a1-ne-zero"}[] its leading coefficient $`c_1'` is nonzero. The difference $`h-c_1'f` has
vanishing coprime coefficients ({bpref "coeff-eq-a1-lambda"}[] and $`a_1(f)=1`), so it lies in the old
subspace by \[Miy, Thm 4.6.8\]; and $`h` itself, being a form essentially of level $`M\neq N`, also lies in the
old subspace. Therefore
$$`
  f \;=\; c_1'^{-1}h - c_1'^{-1}(h-c_1'f)
`
exhibits $`f` as an element of the old subspace. This contradicts $`f` being a nonzero newform (the new and
old subspaces meet only in $`0`). Hence $`g^{(2)}=0`.

Uses: {uses "newform"}[] {uses "oldPart"}[] {uses "a1-ne-zero"}[] {uses "eigenform-decomp"}[]
:::

:::theorem "smo-constMul" (lean := "HeckeRing.GL2.strongMultiplicityOne_constMul")
*Strong Multiplicity One, Miyake 4.6.12.*
Let $`f` be a normalised newform in $`S_k(N,\chi)`, and let $`g` be any cusp-form Hecke eigenfunction in
$`S_k(N,\chi)`. If $`f` and $`g` are common eigenfunctions of $`T(n)` with the same eigenvalue $`\lambda_n` for
every $`n` with $`(n,N)=1` outside a finite set $`S`, then $`g` is a constant multiple of $`f`:
$$`
  g \;=\; c\,f \qquad\text{for some } c\in\mathbb{C}.
`

Depends on: {uses "newform"}[] {uses "eigenform"}[] {uses "oldPart"}[] {uses "newPart"}[] {uses "newPart-eq-smul"}[] {uses "oldPart-eq-zero"}[]
:::

:::proof "smo-constMul"
This is \[Miy, Thm 4.6.12\]. Normalise $`a_1(f)=1`, which is legitimate since $`a_1(f)\neq 0` by
\[Miy, Lemma 4.6.11\], and split $`g` along the orthogonal new/old decomposition,
$`g=g^{(1)}+g^{(2)}` with $`g^{(1)}\in S_k^{\sharp}(N)` and $`g^{(2)}\in S_k^{\flat}(N)`. Because both the new
subspace and the old subspace are stable under the Hecke operators (DS Prop 5.6.2 / \[Miy, Lemma 4.6.10\]),
each of $`g^{(1)}` and $`g^{(2)}` is again a common eigenfunction of $`T(n)` sharing $`f`'s eigenvalue
$`\lambda_n` for $`(n,N)=1` outside $`S`.

For the new part, {bpref "newPart-eq-smul"}[] gives $`g^{(1)}=b_1\,f` where $`b_1=a_1(g^{(1)})`: the
difference $`b_1^{-1}g^{(1)}-f` has vanishing coprime coefficients by \[Miy, Lemma 4.5.15(1)\] and therefore
lies in the old subspace by \[Miy, Thm 4.6.8\], while being new, hence is $`0`. For the old part,
{bpref "oldPart-eq-zero"}[] gives $`g^{(2)}=0`: assuming otherwise, one descends $`g^{(2)}` to a
nonzero new eigenform $`h` at a proper divisor sharing $`f`'s eigenvalues (\[Miy, Lemma 4.6.9\],
\[Miy, Lemma 4.6.2\], and linear independence of distinct-eigenvalue eigenforms), and then
$`h-c_1'f\in S_k^{\flat}(N)` together with $`h\in S_k^{\flat}(N)` forces $`f\in S_k^{\flat}(N)`, contradicting
that $`f` is a nonzero newform. Combining the two halves, $`g=g^{(1)}+g^{(2)}=b_1\,f`, so $`g=c\,f` with
$`c=b_1=a_1(g)`.

Uses: {uses "newform"}[] {uses "eigenform"}[] {uses "oldPart"}[] {uses "newPart"}[] {uses "newPart-eq-smul"}[] {uses "oldPart-eq-zero"}[]
:::

:::theorem "smo-clean" (lean := "HeckeRing.GL2.strongMultiplicityOne_axiom_clean")
*Multiplicity One for newforms, DS 5.8.2.*
Let $`f` and $`g` be normalised newforms in the same Nebentypus space $`S_k(N,\chi)`. If $`f` and $`g` have the
same Hecke eigenvalue $`\lambda_n` for every $`n` with $`(n,N)=1` outside a finite set $`S`, then $`f=g`.

Depends on: {uses "smo-constMul"}[] {uses "newform"}[]
:::

:::proof "smo-clean"
This is \[DS, Thm 5.8.2\] and follows immediately from the headline {bpref "smo-constMul"}[]. Applying
it to the newform $`f` and the eigenfunction $`g` produces a constant $`c` with $`g=c\,f`. Comparing first
Fourier coefficients and using that both forms are normalised, $`1=a_1(g)=c\,a_1(f)=c`, so $`c=1` and hence
$`g=f`.

Uses: {uses "smo-constMul"}[] {uses "newform"}[]
:::
